### ISSUE TITLE
mkdocs serve issue with module 'griffe.collections'

### ISSUE THREAD

**Issue by maihoangbichtram** [industrial-optimization-group/DESDEO#166]
`mkdocs serve`
INFO    -  Building documentation...
INFO    -  [macros] - Macros arguments: {'module_name': 'docs/macros', 'modules': [], 'render_by_default': True, 'include_dir': '', 'include_yaml': [], 'j2_block_start_string':
           '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'on_undefined': 'keep', 'on_error_fail': False, 'verbose': False}
INFO    -  [macros] - Found local Python module 'docs/macros' in: /Users/maihbt/var/www/DESDEO-to-cimmit
INFO    -  [macros] - Found external Python module 'docs/macros' in: /Users/maihbt/var/www/DESDEO-to-cimmit
INFO    -  [macros] - Extra filters (module): ['pretty']
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - explanation/scalarization_methods.md
             - explanation/test_problems.md
             - howtoguides/pareto_navigator.md
**ERROR   -  Error reading page 'api/desdeo_api.md': No module named 'griffe.collections'**
Traceback (most recent call last):
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocs/__main__.py", line 272, in serve_command
    serve.serve(**kwargs)
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 85, in serve
    builder(config)
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocs/commands/build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocs/commands/build.py", line 167, in _populate_page
    page.render(config, files)
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocs/structure/pages.py", line 285, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/markdown/core.py", line 357, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/markdown/blockparser.py", line 117, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/markdown/blockparser.py", line 136, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/markdown/blockparser.py", line 158, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocstrings/extension.py", line 128, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocstrings/extension.py", line 204, in _process_block
    handler = self._handlers.get_handler(handler_name, handler_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocstrings/handlers/base.py", line 475, in get_handler
    module = importlib.import_module(f"mkdocstrings_handlers.{name}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocstrings_handlers/python/__init__.py", line 3, in <module>
    from mkdocstrings_handlers.python.handler import get_handler
  File "/Users/maihbt/Library/Caches/pypoetry/virtualenvs/desdeo-73gcwMS_-py3.12/lib/python3.12/site-packages/mkdocstrings_handlers/python/handler.py", line 14, in <module>
    from griffe.collections import LinesCollection, ModulesCollection
**ModuleNotFoundError: No module named 'griffe.collections'**

**Comment by maihoangbichtram** [comment]
For me, `mkdocs server` runs successfully when `docs/api/` is moved out of `docs`

**Comment by light-weaver** [comment]
https://github.com/mkdocs/mkdocs/discussions/3528

Check this

**Comment by light-weaver** [comment]
try updating the packages and see if it works. If so, we probably need to pin the version numbers to avoid this issue

**Comment by gialmisi** [comment]
Closing this due to inactivity. If the issue persists, feel free to re-open this.
